### ISSUE TITLE
Getting an error "Main: Couldn't create a window"

### ISSUE THREAD

**Issue by dimsuz** [plredmond/GPipe-GLFW#16] opened 2016-04-02 23:03 UTC
I am trying to run an executable I built for a `GPipe-Test` example and I am getting an error:

```
Main: Couldn't create a window
Main: thread blocked indefinitely in an MVar operation
```

Is there a way to find out what's wrong, more specifically?
I suspect this is due to an old OpenGL version supported by my laptop's intel gpu, which is
`OpenGL version string: 2.1 Mesa 11.1.2`

But still I'd like to confirm if this is really the case. And if yes, then does this mean I can't learn GPipe on this hardware?..

**Comment by plredmond** [comment] 2016-05-07 15:48
Sorry for the delay.. You can certainly learn GPipe on VirtualBox, which supports a OpenGL 3 software driver out of the box. (If you install guest additions, you might get a different OpenGL version though.)

I'm not sure of the cause of your particular issue which lead to the deadlock you experienced. I'm re-working GPipe-GLFW currently, and will leave this issue open so that I can test & provide a better error message in the next version.

**Comment by dimsuz** [comment] 2016-05-07 20:48
Ok, thank you for information!

**Comment by plredmond** [comment] 2016-11-09 07:02
I repro'd your issue on my netbook, which doesn't support the correct opengl version. Thanks for the report.

**Comment by plredmond** [comment] 2016-11-10 01:56
Solution, if you're running linux, is to use the [Mesa 3D Software Renderer](http://www.mesa3d.org/envvars.html) by setting the `LIBGL_ALWAYS_SOFTWARE` environmental variable.

**Comment by dimsuz** [comment] 2016-11-10 09:28
Thank you! I will try it once I get my hands on it again :)

**Comment by plredmond** [comment] 2016-11-13 21:46
[glfwCreateWindow](http://www.glfw.org/docs/latest/group__window.html#ga5c336fddf2cbb5b92f65f10fb6043344) says:

> #### Returns
> The handle of the created window, or `NULL` if an [**error**](http://www.glfw.org/docs/latest/intro_guide.html#error_handling) occurred.
> #### Errors
> Possible errors include GLFW_NOT_INITIALIZED, GLFW_INVALID_ENUM, GLFW_INVALID_VALUE, GLFW_API_UNAVAILABLE, GLFW_VERSION_UNAVAILABLE, GLFW_FORMAT_UNAVAILABLE and GLFW_PLATFORM_ERROR.

This sounds promising, however the [error handling page](http://www.glfw.org/docs/latest/intro_guide.html#error_handling) just says to set an error callback. By default, GPipe-GLFW [sets the error callback](https://github.com/plredmond/GPipe-GLFW/blob/b92040e5a4f3460a12cd7fd331db9380f358c03a/GPipe-GLFW/src/Graphics/GPipe/Context/GLFW/Resource.hs#L59) to [print the message and quit](https://github.com/plredmond/GPipe-GLFW/blob/b92040e5a4f3460a12cd7fd331db9380f358c03a/GPipe-GLFW/src/Graphics/GPipe/Context/GLFW/Resource.hs#L38). That error callback is never invoked.

Since the crash you observed happens as a result of GHC's deadlock detection, it might be the case that GLFW never gets a chance to call it before the program is terminated.

**Comment by plredmond** [comment] 2017-05-04 06:00
The current version of GPipe-GLFW reports (via an IO exception) when window creation fails, has different context and thread handling properties, and the smoketests check for `LIBGL_ALWAYS_SOFTWARE` and report about it. Closing this for the time being.

**Closed by plredmond** 2017-05-04 06:00 UTC
